apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-chart.fullname" . }}
  labels:
    app: {{ include "redis-chart.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redis-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis-chart.name" . }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
